[package]
name = "turn-proxy-client"
version = "1.0.0"
description = "DTLS proxy server for TURN relay"
license-file = "LICENSE"
license = "LGPL-3"
authors = ["Urtyom Alyanov"]
edition = "2024"

[dependencies]
rcgen = "0.13.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2.4"
tokio = { version = "1.50.0", features = ["full"] }
toml = "1.0.6"
webrtc-dtls = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
clap = { version = "4.6.0", features = ["derive"] }
anyhow = "1.0.102"
webrtc-util = { version = "0.11.0", features = ["conn"] }
tokio-util = "0.7.18"

[profile.dist]
inherits = "release"
lto = "thin"